version: "3.1"
services:
    mysql:
      image: mariadb
      container_name: corona-mysql
      working_dir: /application
      volumes:
        - ./docker/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=corona
        - MYSQL_USER=corona
        - MYSQL_PASSWORD=corona
      ports:
        - "8002:3306"
      labels:
        com.symfony.server.service-prefix: 'DATABASE'

    elasticsearch:
      image: elasticsearch:6.8.15
      container_name: corona-elasticsearch
      environment:
        - discovery.type=single-node
        - cluster.routing.allocation.disk.threshold_enabled=true
        - cluster.routing.allocation.disk.watermark.flood_stage=100mb
        - cluster.routing.allocation.disk.watermark.low=500mb
        - cluster.routing.allocation.disk.watermark.high=250mb
      volumes:
        - ./docker/elasticsearch:/usr/share/elasticsearch/data
      ports:
        - "9200:9200"
        - "9300:9300"
      labels:
        com.symfony.server.service-prefix: 'ELASTICSEARCH'